# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6624a238c367756578cc68076945f07a"
application_url = "https://circles-procurement-doubt-rg.trycloudflare.com"
embedded = true
name = "synthetic-data-uploader"
handle = "synthetic-data-uploader"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_inventory,read_inventory,read_orders,write_orders,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://circles-procurement-doubt-rg.trycloudflare.com/auth/callback",
  "https://circles-procurement-doubt-rg.trycloudflare.com/auth/shopify/callback",
  "https://circles-procurement-doubt-rg.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "sf-clothingco.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
